### ISSUE TITLE
关于VIG

### ISSUE THREAD

**Issue by ZhaoYuTJPU** [huawei-noah/Efficient-AI-Backbones#101]
您好，我是一名初学者，请问您在VIG论文中给出的伪代码中，我标黄的部分通道数是否有问题？并且文中的这种线性变换都是通过1*1的卷积来实现的吗？
![image](https://user-images.githubusercontent.com/86563793/175756225-3c8d5bf8-b46d-4cab-935b-c7436c34d466.png)
我标黄的部分通道数是否有问题？

**Comment by ZhaoYuTJPU** [comment]
另外，请问在将图像打成16*16的Patch后，共196个Patch，那每个Patch维度应该是256*3=768，这里是否是像VIT一样有一个线性层来把其特征维度进行了一个转换呢？

**Comment by iamhankai** [comment]
谢谢提醒，标黄部分应该为`hidden_channels`。对于Patch也会做维度变换。

**Comment by ZhaoYuTJPU** [comment]
您好，还有个问题，就是在VIG中MLP层全通过1x1的卷积层实现，这样有什么优势吗？我看到引用的那篇deepgcns也是这样操作的

**Comment by iamhankai** [comment]
对于单个node来说，两者是等价的，只是1x1卷积实现时不用对输入特征做reshape等操作了，所以代码更简洁。

**Comment by Idiom1999** [comment]
您好，看了您的论文与代码真的让我受益匪浅。您的意思是，切分出来的patch是再经过1x1的卷积来构成每个每个节点的特征向量吗？
