### ISSUE TITLE
COCO VIG code

### ISSUE THREAD

**Issue by prinshul** [huawei-noah/Efficient-AI-Backbones#104]
Hi,

Awesome project! Thanks for providing it.

Can you please upload the COCO code?

Thank you.

**Comment by prinshul** [comment]
Thank you. Can we use VIG for segmentation on Coco?

**Comment by iamhankai** [comment]
Yes, we have used ViG in Mask-RCNN.

**Comment by prinshul** [comment]
Thank you.

**Comment by chunxt** [comment]
> We use mmdetection for COCO experiments. Just replacing backbone in it.

I am doing this experiments now for tiny object detection by using MMdet and visdrone dataset, but the RetinaNet model with DeepGCN appears nan loss when running the first epoch. I register the DeepGCN in BACKBONES. I wonder if I should add out_indices in backbones for better suit the FPN.

**Comment by iamhankai** [comment]
@chunxt We used the output features in each stage of Pyramid ViG as the input of FPN.

**Comment by chunxt** [comment]
> @chunxt We used the output features in each stage of Pyramid ViG as the input of FPN.

thanks! I have some trouble in repearing the object dectection experiments(RetinaNet ).  Could I request your retinanet config file about the  backbone of Pyramid ViG?  So I can check my config and thanks very much

**Comment by hezheyuan** [comment]
> > We use mmdetection for COCO experiments. Just replacing backbone in it.
> 
> I am doing this experiments now for tiny object detection by using MMdet and visdrone dataset, but the RetinaNet model with DeepGCN appears nan loss when running the first epoch. I register the DeepGCN in BACKBONES. I wonder if I should add out_indices in backbones for better suit the FPN.


Have you solved this problem？Can I see your configuration file？

**Comment by hezheyuan** [comment]
> > @chunxt We used the output features in each stage of Pyramid ViG as the input of FPN.
> 
> thanks! I have some trouble in repearing the object dectection experiments(RetinaNet ). Could I request your retinanet config file about the backbone of Pyramid ViG? So I can check my config and thanks very much

Can you share your ways to replace  backbone in mmdetection? Thanks!

**Comment by UESTC-XU** [comment]
> 

Could I request your retinanet config file about the backbone of Pyramid ViG? So I can check my config and thanks very much!

**Comment by UESTC-XU** [comment]
> @chunxt We used the output features in each stage of Pyramid ViG as the input of FPN.

Could I request your retinanet config file about the backbone of Pyramid ViG? So I can check my config and thanks very much!
