### ISSUE TITLE
  关于ViG输入维度问题

### ISSUE THREAD

**Issue by chenxi1228** [huawei-noah/Efficient-AI-Backbones#112]
作者您好，在尝试复现您这边的ViG工作时，输入的图片为64x64，在调整代码中输入维度后，训练报错显示torch_edge.py中
_, nn_idx = torch.topk(-dist, k=k) # b, n, k
此处的k值超出范围，请问是否时因为输入图片变小之后，形成的图节点不够多导致此处，knn的k值（原代码为16）会超出范围。

在此之后尝试调整（小）此处k值，但是报上述相同错误

想请问，如果需要调整输入图片的大小，在如上述knn中k值，图节点neighbor中k值，以及其他参数上，需要如何调整以适配？

谢谢！

**Comment by iamhankai** [comment]
谢谢关注。应该不是k的问题，是这里的`max_dilation`要调小，改成`2 * 2 // max(num_knn) `
https://github.com/huawei-noah/Efficient-AI-Backbones/blob/b28d6dbf9a707be7a40b33344362cf0d58981a05/vig_pytorch/pyramid_vig.py#L123

**Comment by fzxwz01** [comment]
Hello, why do I run Vig_ When pytorch, an error will be reported 【dataset_train = dataset(train_dir)】 TypeError: 'module' object is not callable

**Comment by chenxi1228** [comment]
> Hello, why do I run Vig_ When pytorch, an error will be reported 【dataset_train = dataset(train_dir)】 TypeError: 'module' object is not callable

你这个问题我感觉很多种情况首先
`dataset_train = dataset(train_dir)`这句应该是 `dataset_train = Dataset(train_dir)`
其次你是不是检查一下`from timm.data import ImageDataset as Dataset` 这句否导入正确，然后看下你自己是不是建了同名的方法或者文件？

**Comment by abhigoku10** [comment]
@chenxi1228 did u train vig with higher resolution or image dimension ?

**Comment by chenxi1228** [comment]
> @chenxi1228 did u train vig with higher resolution or image dimension ?  

Nope just 64x64.
