### ISSUE TITLE
VIG pretrained weights 

### ISSUE THREAD

**Issue by abhigoku10** [huawei-noah/Efficient-AI-Backbones#116]
@huawei-noah-admin  cna you please share the VIG pretraiend model on google drive or one drive as baidu is not accessible from our end 

THank in advance

**Comment by awur978** [comment]
@huawei-noah-admin, thank you for your great work. I am experiencing the same problem as @abhigoku10 , and I too can not download the VIG pretrained model.

**Comment by iamhankai** [comment]
@abhigoku10 @awur978 Where are you guys? I guess Baidu is accessible everywhere on the world.

**Comment by abhigoku10** [comment]
@iamhankai  unfortunately our firewall blocks the access the Baidu , would you pls share it on google drive or one drive it would be helpful

**Comment by abhigoku10** [comment]
@iamhankai awaiting response !! request you to share the weight files

**Comment by abhigoku10** [comment]
@iamhankai  any update on this thread ???

**Comment by iamhankai** [comment]
Sorry for that. Could you ask https://github.com/huawei-noah/Efficient-AI-Backbones/issues/127 for help?

**Comment by iamhankai** [comment]
@abhigoku10 @awur978 We released the weights at https://github.com/huawei-noah/Efficient-AI-Backbones/releases/tag/pyramid-vig
