### ISSUE TITLE
VIG - Custom dataset

### ISSUE THREAD

**Issue by awur978** [huawei-noah/Efficient-AI-Backbones#117]
Hello, thank you for awesome work, really enjoyed your paper.
I am currently working on how I can apply ViG to my custom dataset.
Can you please provide a small instruction on how your code can be adapted to custom dataset.

For example: in pyramid_vig.py, am I right to assume that the variable num_classes is not generic and only works for imagenet?, if my custom dataset has 100 classes, which other aspect of the code do I need to change and so on?

Finally, the evaluation example you provided,
```
python train.py /path/to/imagenet/ --model pvig_s_224_gelu -b 256 --pretrain_path /path/to/pretrained/model/ --evaluate
```

seems to only work for directory with train and val, what if I have a test set separately and I want to check performance of my trained model against the test set, how do I go about this?

Thank you in advance.

**Comment by iamhankai** [comment]
Thanks for the attention. It's a general question. Please ask Google.
