### ISSUE TITLE
train.py报错

### ISSUE THREAD

**Issue by DemonsHunter** [huawei-noah/Efficient-AI-Backbones#118]
感谢您关于ViG的大量工作和code！

我在运行train.py时遇到这个报错：
```
Traceback (most recent call last):
  File "/data1/yhling/train.py", line 35, in <module>
    from timm.data import Dataset, resolve_data_config, Mixup, FastCollateMixup, AugMixDataset #, create_loader
ImportError: cannot import name 'Dataset' from 'timm.data' 
```

尝试根据IDE提示将Dataset改为dataset，但在train.py:486行“dataset_train = dataset(train_dir)”中提示

`dataset is not callable`

请问该如何解决呢？感谢您的回复！

**Comment by iamhankai** [comment]
你的timm版本不对吧，pip install timm==0.3.2试试

**Comment by scholar-wu** [comment]
新版本timm库，改成from timm.data import ImageDataset

**Comment by goodmorningsi** [comment]
> 感谢您关于ViG的大量工作和code！
> 
> 我在运行train.py时遇到这个报错：
> 
> ```
> Traceback (most recent call last):
>   File "/data1/yhling/train.py", line 35, in <module>
>     from timm.data import Dataset, resolve_data_config, Mixup, FastCollateMixup, AugMixDataset #, create_loader
> ImportError: cannot import name 'Dataset' from 'timm.data' 
> ```
> 
> 尝试根据IDE提示将Dataset改为dataset，但在train.py:486行“dataset_train = dataset(train_dir)”中提示
> 
> `dataset is not callable`
> 
> 请问该如

**Comment by goodmorningsi** [comment]
> 感谢您关于ViG的大量工作和code！
> 
> 我在运行train.py时遇到这个报错：
> 
> ```
> Traceback (most recent call last):
>   File "/data1/yhling/train.py", line 35, in <module>
>     from timm.data import Dataset, resolve_data_config, Mixup, FastCollateMixup, AugMixDataset #, create_loader
> ImportError: cannot import name 'Dataset' from 'timm.data' 
> ```
> 
> 尝试根据IDE提示将Dataset改为dataset，但在train.py:486行“dataset_train = dataset(train_dir)”中提示
> 
> `dataset is not callable`
> 
> 请问该如何解决呢？感谢您的回复！

您好，我运行的时候也遇到了这个问题，请问这个问题您解决了吗？
