### ISSUE TITLE
unexpected params in petrained model

### ISSUE THREAD

**Issue by coallar** [huawei-noah/Efficient-AI-Backbones#121]
![image](https://user-images.githubusercontent.com/66529823/179653120-c93cd3a6-4df6-4962-b932-b8b554fd3c06.png)

Hi, there are some params like: *total_ops, *total_op in the pretrained model, and the value of these params is zero. 
 what is wrong

**Comment by iamhankai** [comment]
Please remove those keys in the pretrained model.
