### ISSUE TITLE
pre-trained weights of ViG

### ISSUE THREAD

**Issue by siyuch-fdu** [huawei-noah/Efficient-AI-Backbones#122]
作者您好@[iamhankai](https://github.com/iamhankai)，感谢您的工作！
我想问下您是否有尝试过在Imagenet-21K数据集上预训练ViG，效果如何呢？

Hi author @[iamhankai](https://github.com/iamhankai), thank you for your work!
I would like to ask if you have tried pre-training ViG on the Imagenet-21K dataset, how does it work?

**Comment by THUeeY** [comment]
We also Imagenet-21K pretrained model. Do you have a plan to provide it? @iamhankai

**Comment by iamhankai** [comment]
Thanks for the attention. We are training ViG on ImageNet-21K now.
