### ISSUE TITLE
关于可视化ViG所得的图（Graph）结构问题

### ISSUE THREAD

**Issue by AlligatorSky1017** [huawei-noah/Efficient-AI-Backbones#123]
尊敬的作者您好，
我想请问一下您们的ViG可视化图（下图）是怎么绘制出来的，经过Grapher输出的特征应该是320 * 14 * 14的，怎么样才能把它绘制成一个14*14的Graph呢？您们是在可视化这一步作了降维处理吗？
另外，我还想问一个很傻的问题：即使作了降维，到了14*14，可以把这个矩阵视作一个邻接矩阵进行绘图吗？里面的数据并不是非1即0的，大部分都是小数，请问您们是在绘图的时候设置了某个阈值吗？

![image](https://user-images.githubusercontent.com/76210043/179924416-aacf324b-0745-49a6-a971-6bb23df6204c.png)

冒昧打扰，忘解答！

**Comment by iamhankai** [comment]
您好，你应该对GNN不是特别了解，可以先看看这篇论文：Deepgcns: Can gcns go as deep as cnns?

**Comment by AlligatorSky1017** [comment]
您好，抱歉这么晚才回，看完您说的论文后对这个过程有了更深的了解，谢谢您！
