### ISSUE TITLE
Graph generation and Isotropic ViG

### ISSUE THREAD

**Issue by Ahmad-Omar-Ahsan** [huawei-noah/Efficient-AI-Backbones#124]
Hi, thank you for uploading the code. 

In the paper it is mentioned that before passing the image to the model the image is passed through a function G to generate a graph G=(V,E). Could you tell me at which file the graph generation code is present? Unfortunately I cannot find it. Is it part of the grapher module?

The repository has code for pyramid ViG,  could you upload the code and weights for isotropic ViG?

Thanks in advance

**Comment by iamhankai** [comment]
Thanks for the attention. The graph is dynamically generated in grapher module. By default, we use MRConv in this repo: https://github.com/lightaime/deep_gcns_torch.

**Comment by StefanYz** [comment]
Hi, same question here, could you please explain more about "The graph is dynamically generated in grapher module" ? does it mean that you generate the graph outside of this repo's code? Or could you please provide a link refer to the grapher module? Great thanks!

**Comment by iamhankai** [comment]
@StefanYz The link to Grapher module: https://github.com/huawei-noah/Efficient-AI-Backbones/blob/0b7c9aea711651fd515948b254e35761b5a7129c/vig_pytorch/gcn_lib/torch_vertex.py#L133

**Comment by Idiom1999** [comment]
您好，您的代码真的让我受益匪浅。请问我想实现isotropic ViG应该怎么调整参数呢？我只看到了金字塔结构的Vig。

**Comment by wukurua** [comment]
我也想知道isotropic ViG的代码在哪里，参数改成 --model vig_s_224_gelu 后报错 RuntimeError: Unknown model (vig_s_224_gelu)，搜索也没找到

**Comment by iamhankai** [comment]
Please refer to https://github.com/huawei-noah/Efficient-AI-Backbones/issues/130

**Comment by iamhankai** [comment]
> 我也想知道isotropic ViG的代码在哪里，参数改成 --model vig_s_224_gelu 后报错 RuntimeError: Unknown model (vig_s_224_gelu)，搜索也没找到

isotropic ViG的代码已发布：https://github.com/huawei-noah/Efficient-AI-Backbones/issues/124#issuecomment-1228207528
