### ISSUE TITLE
关于G-GhostNet

### ISSUE THREAD

**Issue by zhanghao5201** [huawei-noah/Efficient-AI-Backbones#125]
作者您好，我看开源的代码中只有GhostX-RegNet 的代码，没有G-GhostNet的代码，请问G-GhostNet什么时候开源呢？还是说暂时不会开源？

**Comment by iamhankai** [comment]
G-Ghost-RegNet已开源，可以参考来构建G-GhostNet

**Comment by yanjiinghui** [comment]
作者您好，我在“The checkpoint is available at [BaiduDisk](https://pan.baidu.com/s/1bgdM9xWVCFGMyYMKPUn4Zg) and Password: on8i.”处下载的权值存在问题不能解压，我尝试过用其他设备进行同样的操作依然没有解决，能否麻烦您看看上传的权值是否存在问题，谢谢~

**Comment by iamhankai** [comment]
不用解压，直接torch.load啊
