### ISSUE TITLE
The implementation of Isotropic architecture

### ISSUE THREAD

**Issue by buptxiaofeng** [huawei-noah/Efficient-AI-Backbones#130]
Hi, thanks for sharing this impressive work. The paper mentioned two architectures, Isotropic one and pyramid one. I noticed that in the code, this is a reduce_ratios, and this reduce_ratios are used by a avg_pooling operation to calculate before building the graph. I am wondering whether all I need to do is setting this reduce_ratios to [1,1,1,1] if I want to implement the Isotropic architecture. Thanks.

 self.n_blocks = sum(blocks)
 channels = opt.channels
 reduce_ratios = [4, 2, 1, 1]
 dpr = [x.item() for x in torch.linspace(0, drop_path, self.n_blocks)] 
 num_knn = [int(x.item()) for x in torch.linspace(k, k, self.n_blocks)]

**Comment by iamhankai** [comment]
Yes, set this reduce_ratios to [1,1,1,1].

**Comment by HaniItani** [comment]
Hello @iamhankai,

Shouldn't the downsampling be also disabled for the isotropic architecture so that the number of tokens is constant throughout the model?

**Comment by iamhankai** [comment]
Yes, it doesn't need downsampling in the isotropic architecture.

**Comment by githuberiex** [comment]
`for i in range(len(blocks)):
            if i > 0:
                self.backbone.append(Downsample(channels[i-1], channels[i]))`

To implement the Isotropic architecture, I need to do is setting reduce_ratios to [1,1,1,1] and removing this **Downsample**, right?

**Comment by iamhankai** [comment]
Yes. The Isotropic code will be released soon.

**Comment by iamhankai** [comment]
> Yes. The Isotropic code will be released soon.

已发布isotropic ViG的代码：https://github.com/huawei-noah/Efficient-AI-Backbones/tree/master/vig_pytorch
