### ISSUE TITLE
ImportError: cannot import name 'Dataset' from 'timm.data'

### ISSUE THREAD

**Issue by anssandeep** [huawei-noah/Efficient-AI-Backbones#140]
Hello,

Thanks for sharing the code. I am trying to run vig_pytorch and I am getting the Dataset importing issue from timm library. Which version of timm are you using?

**Comment by anssandeep** [comment]
I found the version.

**Comment by Yuri6191** [comment]
what version do you use?

**Comment by iamhankai** [comment]
timm==0.3.2

**Comment by goodmorningsi** [comment]
> 你好
> 
> 感谢您分享代码。我正在尝试运行vig_pytorch并且从 timm 库收到数据集导入问题。您使用的是哪个版本的 timm？



> Hello,
> 
> Thanks for sharing the code. I am trying to run vig_pytorch and I am getting the Dataset importing issue from timm library. Which version of timm are you using?

Hello, could I ask if your vig-pytorch code ran successfully?
