### ISSUE TITLE
MACs or FLOPS in ViG Paper

### ISSUE THREAD

**Issue by asif-hanif** [huawei-noah/Efficient-AI-Backbones#141]
Hi 
Could you please clarify the following ambiguity.

Line 360 of `train.py` computes MACs. 
However, this number is reported as FLOPs in the paper e.g. Table-4 and Table-5.
As I understand that  1 FLOPs = 2 x MACs.
If this is the case, all numbers of **'FLOPs (B)'** column in the tables, corresponding to ViG, should get multiplied by 2.

**Comment by iamhankai** [comment]
In our paper, FLOPs==MACs as in [EfficientNet](https://arxiv.org/pdf/1905.11946.pdf)
