### ISSUE TITLE
question of test

### ISSUE THREAD

**Issue by ModeSky** [huawei-noah/Efficient-AI-Backbones#145]
What causes the following errors in the test report?
![1664332868085](https://user-images.githubusercontent.com/50895544/192675425-a36aed5a-b6c5-4f4d-978d-986dd454b25d.jpg)

**Comment by iamhankai** [comment]
I re-run the code of pvig_m_224_gelu, and succeed. Did you modify the code of pyramid_vig.py?

**Comment by ModeSky** [comment]
您好，我没有更改原模型代码部分




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kai ***@***.***&gt;; 
发送时间: 2022年9月28日(星期三) 下午2:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huawei-noah/Efficient-AI-Backbones] question of test (Issue #145)





 
I re-run the code of pvig_m_224_gelu, and succeed. Did you modify the code of pyramid_vig.py?

**Comment by ModeSky** [comment]
作者您好，我想咨询一下，对于ImageNet数据集体量太大，本人将其缩减到了16万张数据，但使用ViG跑该数据集却显示train的loss一直处于6.5以上，然后test部分top1和5的准确率都很低，请问您能解答一下疑惑吗，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kai ***@***.***&gt;; 
发送时间: 2022年9月28日(星期三) 下午2:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huawei-noah/Efficient-AI-Backbones] question of test (Issue #145)





 
I re-run the code of pvig_m_224_gelu, and succeed. Did you modify the code of pyramid_vig.py?

**Comment by iamhankai** [comment]
请问怎么缩减的数据集？

train loss一直6.5以上，看起来是没收敛，需要训到3左右才好。

**Comment by ModeSky** [comment]
就是选择了test文件夹前10000张图片，train文件夹各子文件夹留前100张图片，val文件夹留取前50000张图片，然后剩下的ILSVRC2012_devkit_t12文件夹未更改




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kai ***@***.***&gt;; 
发送时间: 2022年9月28日(星期三) 下午3:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huawei-noah/Efficient-AI-Backbones] question of test (Issue #145)





 
请问怎么缩减的数据集？
 
train loss一直6.5以上，看起来是没收敛，需要训到3左右才好。

**Comment by iamhankai** [comment]
那你还不如保留100类，每类100张可能有点少

**Comment by ModeSky** [comment]
保留100类的话，test文件夹里包含1000类数据，请问test文件夹如何处理呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kai ***@***.***&gt;; 
发送时间: 2022年9月28日(星期三) 下午3:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huawei-noah/Efficient-AI-Backbones] question of test (Issue #145)





 
那你还不如保留100类，每类100张可能有点少

**Comment by ModeSky** [comment]
您好，请问完成这些操作后形成的数据集还需要生成对应的标签文件吗？例如class.txt和label.txt这种




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/Efficient-AI-Backbones"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 下午3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huawei-noah/Efficient-AI-Backbones] question of test (Issue #145)





 
使用对应的100类做val和test

**Comment by ModeSky** [comment]
作者您好，根据您的意思，我将val的100个文件夹及类留下后，要自己制作test集还是我不需留下test？




Liar.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/Efficient-AI-Backbones"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 下午3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huawei-noah/Efficient-AI-Backbones] question of test (Issue #145)





 
使用对应的100类做val和test

**Comment by iamhankai** [comment]
用不到test

**Comment by ModeSky** [comment]
好的，谢谢
&nbsp;


Liar.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kai ***@***.***&gt;; 
发送时间: 2022年9月29日(星期四) 上午10:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huawei-noah/Efficient-AI-Backbones] question of test (Issue #145)





 
用不到test

**Comment by ModeSky** [comment]
作者您好，根据您的最近几天的解答，我是不是可以理解ViG这个网络架构是个无监督学习的呢？




Liar.
***@***.***



&nbsp;


？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/Efficient-AI-Backbones"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huawei-noah/Efficient-AI-Backbones] question of test (Issue #145)





 
用不到test

**Comment by ModeSky** [comment]
作者您好，想问一下，本人打印train.py、myloader.py以及向上溯源的loader.py中打印target变量时显示如下，是因为未更改参数变量吗？





Liar.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/Efficient-AI-Backbones"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huawei-noah/Efficient-AI-Backbones] question of test (Issue #145)





 
用不到test

**Comment by iamhankai** [comment]
没看到图片

**Comment by ModeSky** [comment]
Liar.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/Efficient-AI-Backbones"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月30日(星期五) 上午10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huawei-noah/Efficient-AI-Backbones] question of test (Issue #145)





 
没看到图片

**Comment by ModeSky** [comment]
作者您好，我刚刚训练一下代码，数据集是100类，但是目前来看好像不太对





Liar.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/Efficient-AI-Backbones"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月30日(星期五) 上午10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huawei-noah/Efficient-AI-Backbones] question of test (Issue #145)





 
没看到图片

**Comment by ModeSky** [comment]
作者您好，请问这种情况是数据集未处理好，导致程序未读取到标签还是myloader中的参数和我的环境有所差异，打印train中的target显示乱码，导致test时acc的值大于1，误差很大







Liar.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/Efficient-AI-Backbones"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月30日(星期五) 上午10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huawei-noah/Efficient-AI-Backbones] question of test (Issue #145)





 
没看到图片

**Comment by ModeSky** [comment]
好的，谢谢您






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kai ***@***.***&gt;; 
发送时间: 2022年9月28日(星期三) 下午3:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huawei-noah/Efficient-AI-Backbones] question of test (Issue #145)





 
使用对应的100类做val和test

**Comment by goodmorningsi** [comment]
> What causes the following errors in the test report? ![1664332868085](https://user-images.githubusercontent.com/50895544/192675425-a36aed5a-b6c5-4f4d-978d-986dd454b25d.jpg)
您好，我也遇到了这个问题，请问这个问题要怎么解决呢？

**Comment by goodmorningsi** [comment]
请问楼主可以留个邮箱吗，有些问题想要向你请教
