### ISSUE TITLE
数据加载问题

### ISSUE THREAD

**Issue by ModeSky** [huawei-noah/Efficient-AI-Backbones#149]
请问这种情况是数据集未处理好，导致程序未读取到标签还是myloader中的参数和我的环境有所差异，打印train中的target显示乱码，导致test时acc的值大于1，误差很大
![image](https://user-images.githubusercontent.com/50895544/193719552-e166e4ae-347b-471e-8285-857d615a3922.png)

**Comment by iamhankai** [comment]
同学你好，你提了好几个issue，看起来都是很基础的问题。你应该好好打基础，至少把pytorch用熟练了，再去做更深入的科研。我建议你先学习一下pytorch官方的教程：https://pytorch.org/tutorials/beginner/pytorch_with_examples.html

**Comment by ModeSky** [comment]
好的，谢谢您，给您添麻烦了，实在是抱歉
