### ISSUE TITLE
模型加载问题

### ISSUE THREAD

**Issue by isJunCheng** [huawei-noah/Efficient-AI-Backbones#150]
在模型加载时遇到问题，模型权重不在data.pkl中吗?
![image](https://user-images.githubusercontent.com/44466856/194712987-fdf7001a-82a0-4799-91c2-a3a6eb290b4a.png)

是因为训练和推理时的torch版本不一致吗？我已经按照要求安装了如下环境：
![1665239877942](https://user-images.githubusercontent.com/44466856/194712893-fb227b75-697d-4fd0-b4b2-10681e485eac.png)
请问这是什么原因呢？

**Comment by isJunCheng** [comment]
@iamhankai

**Comment by iamhankai** [comment]
直接加载pvig_s_82.1.pth.tar，不用解压：`torch.load('pvig_s_82.1.pth.tar')`

**Comment by isJunCheng** [comment]
> 直接加载pvig_s_82.1.pth.tar，不用解压：`torch.load('pvig_s_82.1.pth.tar')`

非常感谢您的回复。顺便问一下，没有直接推理的代码吗

**Comment by iamhankai** [comment]
The inference code is included in train.py.

inference example:

`python train.py /path/to/imagenet/ --model pvig_s_224_gelu -b 128 --pretrain_path /path/to/pretrained/model/ --evaluate
`
