### ISSUE TITLE
ViG实现是否使用了multi-head

### ISSUE THREAD

**Issue by linhaojia13** [huawei-noah/Efficient-AI-Backbones#153]
作者你好！论文中提到使用了multi-head设计，并且head数量为4，“. We select h = 4 as default value for the optimal trade-off between FLOPs and accuracy.”。但是我在`class Grapher`、`class DyGraphConv2`、`class GraphConv2`、`class MRConv2d`的代码中均没有发现使用了multi-head。请问是我哪里理解错误或者遗漏了吗？

**Comment by iamhankai** [comment]
这里groups=4是可以方便地实现multi-head部分：https://github.com/huawei-noah/Efficient-AI-Backbones/blob/033ccb8bce2b56e9e0b03b3a7c1c2f960ee0b23f/vig_pytorch/gcn_lib/torch_nn.py#L58

**Comment by linhaojia13** [comment]
原来如此，谢谢！
