### ISSUE TITLE
关于VIG预训练模型版本问题

### ISSUE THREAD

**Issue by wanghonen** [huawei-noah/Efficient-AI-Backbones#154]
您好，我在使用VIG预训练模型时发现无法在Pytorch 1.7.0版本下使用，想询问您一下，保存预训练模型的Pytorch版本应该不是 1.7.0吧？我应该使用什么版本呢

**Comment by iamhankai** [comment]
预训练模型的Pytorch版本也是Pytorch 1.7.0，请问你报什么错误了？

**Comment by wanghonen** [comment]
不好意思，是我输入的预训练模型格式有问题，解决了这个问题之后，我使用你们提供的python train.py /path/to/imagenet/ --model pvig_s_224_gelu -b 128 --pretrain_path /path/to/pretrained/model/ --evaluate这个语句测试模型效果，我的数据文件夹里面只有有test和val文件夹，但是程序提示我需要有train文件夹，我不太理解（因为我是新手），为什么还需要训练数据，我就只想用你们提供的预训练模型来测试，请问能解答一下吗？有什么办法解决我的问题，感谢

**Comment by iamhankai** [comment]
是imagenet dataloader需要train文件夹，实际上在测试时不会用，你可以创建一个假的train文件夹
