### ISSUE TITLE
请问会有ghostnetv2的pytorch预训练权重嘛？

### ISSUE THREAD

**Issue by GitHubyu007** [huawei-noah/Efficient-AI-Backbones#160]
非常感谢你们的工作，请问会有ghostnetv2的pytorch预训练权重嘛，如果出这个预训练权重是基于哪个数据集什么进行训练的呢？
另外在MindSpore上的ghostnetv2权重类型是ckpt，现在我尝试转换成pth，并跑一下自己的模型看下这个预训练权重效果怎么样。

**Comment by yehuitang** [comment]
预训练模型已经公开https://github.com/huawei-noah/Efficient-AI-Backbones/releases/tag/GhostNetV2，基于ImageNet训练的。
