### ISSUE TITLE
ghostnetv2预训练权重问题

### ISSUE THREAD

**Issue by Nameggy** [huawei-noah/Efficient-AI-Backbones#164]
您好 我使用
model = ghostnetv2()
state_dict = torch.load('.\ck_ghostnetv2_10.pth.tar')
model.load_state_dict(state_dict)
以上代码进行加载，提示报错是Unexpected key(s) in state_dict: "total_ops", "total_params"......等权重不匹配问题 这是为何呢

**Comment by yehuitang** [comment]
You can set 'strict=False' in function 'load_state_dict'.
