### ISSUE TITLE
GhostNetv2报错

### ISSUE THREAD

**Issue by River-Cold** [huawei-noah/Efficient-AI-Backbones#170]
ghostnetv2_torch.py缺少测试的代码，我尝试添加ghostnet.py中的测试代码来测试网络功能
![image](https://user-images.githubusercontent.com/80696033/206892399-0a358e0c-909f-498f-a31d-b4b54893cfdc.png)
但发现测试过程中出现了报错
`RuntimeError: The size of tensor a (80) must match the size of tensor b (64) at non-singleton dimension 2`
详细报错信息如下：
![image](https://user-images.githubusercontent.com/80696033/206892429-3b8a8d4a-0bc6-4530-b570-982c46378657.png)
在网上查找了一些解决方案有提到是网络本身定义有错误，我猜测是ghost和dfc注意力机制相乘的部分存在问题，可以麻烦您帮忙排查一下这个错误吗？不胜感激！

**Comment by gusario** [comment]
For now I'm advising you to use this implementation of ghostnetv2 https://github.com/rwightman/pytorch-image-models/blob/cf5ac2800cb6c6d151a5fce55d77614d864534d5/timm/models/ghostnet.py, it supports any  input sizes. Even though comments in code say that it's original ghostnet, forward pass structure and everything else look similar to this implementation, so I think it actually is ghostnetv2. If I'm mistaken, please feel free to correct me

**Comment by yehuitang** [comment]
Thanks for your good question! The released code has be updated to tackle input with height != width.  

Only a line of code is updated, i.e.,
return out[:,:self.oup,:,:]*F.interpolate(self.gate_fn(res),size=out.shape[-1],mode='nearest') 
to
return out[:,:self.oup,:,:]*F.interpolate(self.gate_fn(res),size=(out.shape[-2],out.shape[-1]),mode='nearest')
