### ISSUE TITLE
tnt_s_81.5

### ISSUE THREAD

**Issue by armin-azh** [huawei-noah/Efficient-AI-Backbones#172]
Hi, according to the Internet Limitation in my country, I cannot download the tnt_s_81.5 pre-trained model in Baidu Network Dist. Do you mind if I ask you to upload the pre-trained weights in another storage like Google Drive?

**Comment by iamhankai** [comment]
https://github.com/contrastive/pytorch-image-models/releases/download/TNT/tnt_s_patch16_224.pth.tar

**Comment by armin-azh** [comment]
Thanks:)
