### ISSUE TITLE
关于Ghostnetv2预训练模型不同width的问题

### ISSUE THREAD

**Issue by ZKH66** [huawei-noah/Efficient-AI-Backbones#177]
您好，请问不同width的ghostnetv2预训练权重在加载时需要更改model中的哪些部分，因为我使用width=1.0时不需要更改什么，直接训练下来acc开始就达到7、80%，但width=1.6的权重感觉没有加载成功？

**Comment by ibanana97** [comment]
请问楼主知不知道这个1.0、1.3、1.6各自的cfgs分别是多少，现在给出的cfgs好像默认是1.0的

**Comment by iamhankai** [comment]
See https://github.com/huawei-noah/Efficient-AI-Backbones/issues/180#issuecomment-1484670285
