### ISSUE TITLE
VIG运行报错：UnboundLocalError: local variable 'input' referenced before assignment

### ISSUE THREAD

**Issue by worker121** [huawei-noah/Efficient-AI-Backbones#179]
尊敬的作者，您好！
我在运行您的代码的时候遇到了这样的报错：
Traceback (most recent call last):
  File "train.py", line 809, in <module>
    main()
  File "train.py", line 603, in main
    train_metrics = train_epoch(
  File "train.py", line 662, in train_epoch
    for batch_idx, (input1, target) in enumerate(loader):
  File "/opt/conda/lib/python3.8/site-packages/timm/data/loader.py", line 102, in __iter__
    yield input, target
UnboundLocalError: local variable 'input' referenced before assignmen
我的运行环境和readme文件中的一致，请问这个要怎么解决呢？

**Comment by iamhankai** [comment]
看日志是你的data loader没加载对，是不是数据集是空的啊

**Comment by iamhankai** [comment]
1个类别怎么分类啊，多放几个类别

**Comment by worker121** [comment]
因为数据集太大了，放在服务器集群上了，想在本地测试下代码能不能正常运行，所以本地的数据类别数量有限，目前放了几个类别上去还是报一样的错

**Comment by worker121** [comment]
您好，我使用全部的数据集按照[extract_ILSVRC.sh]里提取的格式试着运行了下，但又遇到错误说train路径下没有数据，报错如下：
Training with a single process on 1 GPUs.
Model vig_s_224_gelu created, param count: 22747752
Data processing configuration for current model + dataset:
	input_size: (3, 224, 224)
	interpolation: bicubic
	mean: (0.5, 0.5, 0.5)
	std: (0.5, 0.5, 0.5)
	crop_pct: 0.9
Using native Torch AMP. Training in mixed precision.
Scheduled epochs: 310
ERROR: Training folder does not exist at: /public_datasets/data/ImageNet2012/imagenet/train
我的数据分布如下：
imagenet/train/
#  ├── n01440764
#  │   ├── n01440764_10026.JPEG
#  │   ├── n01440764_10027.JPEG
#  │   ├── ......
#  ├── ......
imagenet/val/
#  ├── n01440764
#  │   ├── ILSVRC2012_val_00000293.JPEG
#  │   ├── ILSVRC2012_val_00002138.JPEG
#  │   ├── ......
#  ├── ......
请问这个是怎么回事？

**Comment by worker121** [comment]
感谢您的热心帮助，代码可以正常运行了

**Comment by colayear** [comment]
您好，我也遇到了同样的问题，我放了两个类别图片后，print了一下timm的dataset，发现图片应该是正常进入数据集的。
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/55417141/221464857-a98a2c87-c967-4b5d-a010-b255f9760947.png">

但是还是出现这个报错，请问这该怎么解决呢？
