### ISSUE TITLE
关于GhostNetv2网络的cfgs设计

### ISSUE THREAD

**Issue by Ifjmww** [huawei-noah/Efficient-AI-Backbones#180]
作者您好，感谢您的工作！
我对于GhostNetv2的cfgs设计有一些疑问：
1.网络的cfgs为什么要设定成这些参数，更换其他的参数可以么？

```
cfgs = [ 
        # k, t, c, SE, s
        [[3, 16, 16, 0, 1]],
        [[3, 48, 24, 0, 2]],
        [[3, 72, 24, 0, 1]],
        [[5, 72, 40, 0.25, 2]],
        [[5, 120, 40, 0.25, 1]],
        [[3, 240, 80, 0, 2]],
        [[3, 200, 80, 0, 1],
         [3, 184, 80, 0, 1],
         [3, 184, 80, 0, 1],
         [3, 480, 112, 0.25, 1],
         [3, 672, 112, 0.25, 1]
         ],
        [[5, 672, 160, 0.25, 2]],
        [[5, 960, 160, 0, 1],
         [5, 960, 160, 0.25, 1],
         [5, 960, 160, 0, 1],
         [5, 960, 160, 0.25, 1]
         ]
]
```

2.如果使用GhostNetv2进行语义分割的话，是需要把整个GhostNetv2作为backbone么，还是只需要GhostBottleneckv2+segmentation head（Deeplabv3、U-Net等等）

**Comment by ibanana97** [comment]
请问楼主知不知道这个1.0、1.3、1.6各自的cfgs分别是多少，现在给出的cfgs好像默认是1.0的

**Comment by iamhankai** [comment]
https://github.com/huawei-noah/Efficient-AI-Backbones/blob/9172762a38e9bcafab9907c93ca7141797386f4c/ghostnetv2_pytorch/model/ghostnetv2_torch.py#L259

把width改成1.0、1.3、1.6就可以了
