### ISSUE TITLE
VIG报错：UnboundLocalError: local variable 'input' referenced before assignment

### ISSUE THREAD

**Issue by colayear** [huawei-noah/Efficient-AI-Backbones#182]
我按照这个issue里解答的方式修改 #179 
我的路径是
<img width="130" alt="image" src="https://user-images.githubusercontent.com/55417141/221470628-c91cd866-c17f-460f-bad2-920003e5d6c8.png">

我放了两个类别图片，也修改了num_classes=2，然后print了一下timm的dataset，发现图片应该是正常进入数据集的。

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/55417141/221470504-8f48e10d-50ca-4c56-8a4c-1a413d9aefa0.png">

但还是出现这个报错，请问这该怎么解决呢？

**Comment by iamhankai** [comment]
我怀疑图片数太少了，没达到一个batch的数量要求

**Comment by colayear** [comment]
> 我怀疑图片数太少了，没达到一个batch的数量要求

我修改了batch_size=2也不能解决

**Comment by iamhankai** [comment]
你这里相对路径能改成绝对路径试试吗

**Comment by colayear** [comment]
> > 你这里相对路径能改成绝对路径试试吗
> 
> <img alt="image" width="1246" src="https://user-images.githubusercontent.com/55417141/221522582-80bb406e-28b3-423d-aedb-472d67d37997.png">

您好，可以帮忙看一下吗

**Comment by colayear** [comment]
试出来了，每一类至少得有128张图片，127张图片报错，128张图片正常运行。（推测是timm.dataloader里默认要求每一个batch_size是128，但不细究了）
