### ISSUE TITLE
ViG在其他数据集上的效果不佳

### ISSUE THREAD

**Issue by zhaoxixixi** [huawei-noah/Efficient-AI-Backbones#184]
首先感谢作者出色的工作！

我是一名科研小白，复现自己数据集时出现错误，想请教应该如何修改模型进行迁移学习，谢谢！
## 以下是我做的工作
​	我将模型prediction最后一层改为100类，并降低学习率后。在训练时test的准确率一直在提高，同时ACC1和ACC5在不同程度地提高，而Test（EMA）提升的比较缓慢。同时在使用此训练过后的预训练模型进行测试，效果不佳。

模型修改的部分：
![image](https://user-images.githubusercontent.com/66891417/222363108-e61f538b-fda7-4668-9a55-8c911b632dab.png)
将最后一层1000类别改为100类别，train.py代码处修改为：（加载参数之后修改模型）

![image](https://user-images.githubusercontent.com/66891417/222363183-12dbc2b8-2855-48b0-9cb1-5cc8ab3f9c8a.png)

在进行预测时，将代码修改为（先修改模型，再加载参数）

同时在加载以此为基础的训练模型，train.py代码修改为：

![image](https://user-images.githubusercontent.com/66891417/222363235-f9cb38dc-50ee-4106-9057-e0fcc5a6e80a.png)

训练命令：

![image](https://user-images.githubusercontent.com/66891417/222363265-968793c5-12f3-4831-82b7-273a5e7210c9.png)
训练时loss以及正确率：

![image](https://user-images.githubusercontent.com/66891417/222363296-453a0ad2-363f-45c8-b7e4-75e8ad5caa30.png)
预测命令：

![image](https://user-images.githubusercontent.com/66891417/222363348-5f438911-bbc7-4510-8b27-6f9a919117f8.png)
best_md.pth是以我的数据集训练得到的预训练模型。

预测时的loss：

![image](https://user-images.githubusercontent.com/66891417/222363395-5e0964fc-d21a-4d07-8647-56811534d52e.png)
测试数据：miniImgNet

train：100类，每类480张

![image](https://user-images.githubusercontent.com/66891417/222363442-ad0d7ae4-0e3f-42b8-b9e5-2dca75c3c19e.png)
val：100类，每类120张

![image](https://user-images.githubusercontent.com/66891417/222363474-bee1c7d9-049d-4a3c-8687-85b84930e8e4.png)
## 问题

请问我这样修改模型是否正确？应该如何修改模型才能迁移学习到我目前的数据集呢？

**Comment by iamhankai** [comment]
- 你的train loss看起来很正常。Test（EMA）提升的比较缓慢是正常的，要训的epoch数多（200epochs），Test（EMA）才会更高。
- 你预测时的loss太大了，不正常，是不是model没加载成功啊。

**Comment by zhaoxixixi** [comment]
作者您好！
非常感谢您的答复，问题已解决！
再次感谢您优秀的工作！

**Comment by yankwi** [comment]
> 作者您好！ 非常感谢您的答复，问题已解决！ 再次感谢您优秀的工作！

大佬请问下，您最后是如何解决的呢？我现在也出现一样的问题。

**Comment by zhaoxixixi** [comment]
> 

我是模型没加载成功导致的，具体你可以输出一下模型加载后的**权重参数**，如果出现大面积都是全0这种情况，你就需要看一下是定义模型和你记载模型参数的张量维度大小是不是一样的。

**Comment by yankwi** [comment]
您好，邮箱已收到，我会尽快给您回复。

**Comment by yankwi** [comment]
谢谢 已经解决。问题出在多卡训练单卡推理，模型名称不匹配(多卡模型名多了“module”), 可如下修改：model.load_state_dict(checkpoint['state_dict'], strict=False)

**Comment by PoisonKiller** [comment]
> > 
> 
> 我是模型没加载成功导致的，具体你可以输出一下模型加载后的**权重参数**，如果出现大面积都是全0这种情况，你就需要看一下是定义模型和你记载模型参数的张量维度大小是不是一样的。

请问哥你是怎么解决这个问题的呀，能参考下你的代码吗？最近也遇到了这个问题但是不知道如何解决，谢谢！

**Comment by yankwi** [comment]
您好，邮箱已收到，我会尽快给您回复。
