### ISSUE TITLE
model直接加载ghostnetv2的预训练权重

### ISSUE THREAD

**Issue by SoramiAkito** [huawei-noah/Efficient-AI-Backbones#198]
<img width="626" alt="Snipaste_2023-04-19_10-48-04" src="https://user-images.githubusercontent.com/84394065/232954193-9553cc8a-9a57-4448-b9a2-273ad42066b5.png">
使用model.load_state_dict(state_dict)加载提供的pth权重时提示了这个错误
<img width="1133" alt="Snipaste_2023-04-18_20-56-18" src="https://user-images.githubusercontent.com/84394065/232954289-e085f2d3-6778-4315-970f-24d732935291.png">
是需要进行什么名称的修改吗？

**Comment by iamhankai** [comment]
参考 https://github.com/huawei-noah/Efficient-AI-Backbones/issues/175

**Comment by SoramiAkito** [comment]
> 参考 #175

感谢！
