### ISSUE TITLE
VIG节点连边问题

### ISSUE THREAD

**Issue by worker121** [huawei-noah/Efficient-AI-Backbones#200]
您好！ 
您论文中所提及的对于VIG构建节点之后选择K个最近邻的邻居来建边。请问这个最近邻是怎么定义的？
我看您的代码中在class DenseDilated(nn.Module):中将计算获得的节点之间的pairwise distance直接使用edge_index = edge_index[:, :, :, ::self.dilation]进行切片处理，这样处理后的节点的k个邻居貌似就直接是每隔dilation个距离就取一个当邻居，请问这怎么体现最近邻的概念呢？

**Comment by iamhankai** [comment]
这个是dilated GCN的概念，可以参考论文sec3.4：https://openaccess.thecvf.com/content_ICCV_2019/papers/Li_DeepGCNs_Can_GCNs_Go_As_Deep_As_CNNs_ICCV_2019_paper.pdf

**Comment by worker121** [comment]
哦哦，好的，谢谢您
