### ISSUE TITLE
Regnet code

### ISSUE THREAD

**Issue by xiaobaitubaibaibai** [huawei-noah/Efficient-AI-Backbones#206]
Dear author:
     Where can I find the regnet source code you used?

**Comment by iamhankai** [comment]
https://github.com/huawei-noah/Efficient-AI-Backbones/tree/master/g_ghost_pytorch

**Comment by xiaobaitubaibaibai** [comment]
> https://github.com/huawei-noah/Efficient-AI-Backbones/tree/master/g_ghost_pytorch

Thank for your reply!
