### ISSUE TITLE
tnt_b_82.9 pre-trained model

### ISSUE THREAD

**Issue by k6s7h7** [huawei-noah/Efficient-AI-Backbones#207]
Hi, according to the Internet Limitation in my country, I cannot download the tnt_b_82.9 pre-trained model in Baidu Network Disk. Do you mind if I ask you to upload the pre-trained weights in another storage like Google Drive?

**Comment by iamhankai** [comment]
Sorry for late reply. tnt_b_82.9 can be downloaded from https://github.com/huawei-noah/Efficient-AI-Backbones/releases/download/tnt/tnt_b_82.9.pth.tar

**Comment by n0kovo** [comment]
@iamhankai Could you upload the missing pre-trained PyramidTNT models too?

The ones that are missing are:
`ptnt-s-82.0.pth.tar`
`ptnt-b-84.1.pth.tar`

Thanks!
