### ISSUE TITLE
for the running bug of the vig

### ISSUE THREAD

**Issue by ZeroerWiser** [huawei-noah/Efficient-AI-Backbones#210]
THe device is equiped with 2 gpu, after i processed the data ,following your prompt and running the training command of "python -m torch.distributed.launch --nproc_per_node=2 train.py imagenet --model vig_s_224_gelu --sched cosine --epochs 300 --opt adamw -j 2 --warmup-lr 1e-6 --mixup .8 --cutmix 1.0 --model-ema --model-ema-decay 0.99996 --aa rand-m9-mstd0.5-inc1 --color-jitter 0.4 --warmup-epochs 20 --opt-eps 1e-8 --repeated-aug --remode pixel --reprob 0.25 --amp --lr 2e-3 --weight-decay .05 --drop 0 --drop-path .1 -b 128 --output models --num-gpu 2". It makes mistake and show the error is "error: unrecognized arguments: --local-rank=0".Could you help me or show me the solution?

**Comment by iamhankai** [comment]
是torch版本的问题，改成1.7

**Comment by ZeroerWiser** [comment]
> 是torch版本的问题，改成1.7

非常感谢你的回复，我已经解决这个问题了。但运行模型时遇到了图片数据的问题，首先可能由于是服务器内存不足我是边删之前的数据边下载imagenet数据集，有一千多张照片的空的，我将这些空的照片给移出来了。然后训练模型时遇到了“OSError: Caught OSError in DataLoader worker process 2.”与“OSError: Truncated File Read”这2个问题，请问该如何解决呢。我找到的解决方法是通过piilow库将图片解码成tgb格式，请问可行吗

**Comment by ZeroerWiser** [comment]
> 是torch版本的问题，改成1.7

您好请问如何解决图像在处理时被截断的报错呢，报错语句是OSError: image file is truncated (5 bytes not processed)和OSError: Caught OSError in DataLoader worker process 2

**Comment by iamhankai** [comment]
你这个图片是坏的，删了他

**Comment by ZeroerWiser** [comment]
> 你这个图片是坏的，删了他

你好，我想请问如何理解每个patch所形成的节点特征的多样性呢，可以说是节点类型吗，也就是说ViG从图模型的类型来讲算是异构图？

**Comment by iamhankai** [comment]
ViG从图模型角度来讲还是同构图，因为每个节点都是图像patch的特征，是同质的。

**Comment by ZeroerWiser** [comment]
> ViG从图模型角度来讲还是同构图，因为每个节点都是图像patch的特征，是同质的。

非常感谢您的回答，我最后还想问的是K近邻中的k是指选取连边节点的个数吗，我看deepgcn那篇文章里dilated聚合方式里的这个也不太理解，这个有根据相似度分数排序和一个阈值去调整个数的吗？

**Comment by iamhankai** [comment]
对，k是指选取连边节点的个数

**Comment by ZeroerWiser** [comment]
> 对，k是指选取连边节点的个数

那请问为什么会出现[#issue133](https://github.com/huawei-noah/Efficient-AI-Backbones/issues/133)中的用户提问的问题呢：
在定义Grapher类时，您将dilation设置为min(idx//4+1, max_dilation)。然后我调试了代码，令K=9，发现实际上它找的是18或27个近邻。

**Comment by goodmorningsi** [comment]
> 对，这就是dilated聚合方式的做法
作者您好，我将pyramid-vig的network输出特征直接用于检测任务中发现效果不是很好，我想尝试将模型中的不同size的特征图进行特征融合（fpn或者别的方法），然后再看看效果，所以想问问作者，我应该对网络中哪几层的特征进行特征融合效果可能会好一些呢？谢谢

**Comment by iamhankai** [comment]
每个stage的最后一层比较好
