### ISSUE TITLE
关于ViG邻居可视化绘图的疑问

### ISSUE THREAD

**Issue by Joazs** [huawei-noah/Efficient-AI-Backbones#211]
您好，请问VIG论文中的图4是如何绘制出来的？
我打印了edge_index。但是它的大小与原图大小不相同。我知道如何找到节点邻居与原图patch的对应位置关系。
但是我现在做的是像素级分割的任务，我想找到节点邻居与原图上的像素位置对应关系，请问我应该怎么做？

**Comment by iamhankai** [comment]
edge_index存储了2个数组，第一个数组是query的id，第二个数组是和query相连的node的id
