### ISSUE TITLE
图表示是如何转成tensor

### ISSUE THREAD

**Issue by goodmorningsi** [huawei-noah/Efficient-AI-Backbones#212]
作者您好！我看了下DeepGCN这篇文章，里面几个GCN Backbone的输入输出都是以图表示，您提出的VIG的模型应该是通过stem模块将图片转成图的格式吧，但是为什么stem的输出是tensor的形式呢。还有在Grapher部分中进行图卷积处理的时候，输入是以张量的形式输入的吗？这部分的输出的形式是什么呢？因为我看模型里DeepGCN的最终输出是一个张量，所以对其中的图处理的input和output有点困惑，希望能得到大佬的帮助，打扰了哈😀

**Comment by iamhankai** [comment]
1. 一个Graph包含2部分：节点特征和邻接矩阵，节点特征是用tensor来存的，而邻接矩阵是edge_index来存的。

**Comment by goodmorningsi** [comment]
![b557d0c390326c97d44ab31b5a91144](https://github.com/huawei-noah/Efficient-AI-Backbones/assets/97372086/ea7cc9d3-50ba-4d59-9f06-64054fb2357b)

**Comment by goodmorningsi** [comment]
大佬，是这两行代码吧

**Comment by iamhankai** [comment]
是的

**Comment by goodmorningsi** [comment]
好的，大佬，我悟了，salute🫡
