### ISSUE TITLE
VIG与VIT的性能开销

### ISSUE THREAD

**Issue by Viot-HUST** [huawei-noah/Efficient-AI-Backbones#216]
作者您好，请问图卷积与Transformer相比，图卷积对显存占用以及速度上有优势吗？

**Comment by iamhankai** [comment]
相比all-to-all的attention计算，图卷积在理论上说有优势的，但是这需要依赖图卷积的高效底层库实现。

**Comment by Viot-HUST** [comment]
好的，谢谢您的回复。
