### ISSUE TITLE
Training Error on ViG

### ISSUE THREAD

**Issue by Divs1159** [huawei-noah/Efficient-AI-Backbones#220]
First off, amazing work, and thank you very much for sharing the code !

I am facing a issue when training. I got the error:
![image](https://github.com/huawei-noah/Efficient-AI-Backbones/assets/59015654/72440d0b-d1db-4b7b-a625-41297e29261d)

I am using timm version 0.3.2. can you please help me

**Comment by Divs1159** [comment]
Sorry, solved the issue. It was with the folder structure.

I have another doubt. If I am using a custom dataset, is it better to use the pre-trained weights and resume training from there?

**Comment by iamhankai** [comment]
better to use the pre-trained weights
