### ISSUE TITLE
 RuntimeError: Error(s) in loading state_dict for DeepGCN: size mismatch for pos_embed: copying a param with shape torch.Size([1, 192, 14, 14]) from checkpoint, the shape in current model is torch.Size([1, 80, 56, 56]).

### ISSUE THREAD

**Issue by Mrx-yang** [huawei-noah/Efficient-AI-Backbones#226]
After downloading the ImageNet dataset and the pretrained model online，I run the command “python train.py imagenet/train/ --model pvig_s_224_gelu -b 32 --pretrain_path pretrained/vig_ti_74.5.pth --evaluate” ，but occur this mistake above， how do i solve it？

**Comment by iamhankai** [comment]
please refer to https://github.com/huawei-noah/Efficient-AI-Backbones/issues/219
