### ISSUE TITLE
请问如何加载VIG的预训练模型

### ISSUE THREAD

**Issue by leiRabbit1999** [huawei-noah/Efficient-AI-Backbones#228]
在vig.py中，注册模型的代码，例如def vig_b_224_gelu(pretrained=False, **kwargs)，给了一个pretrained的传入参数，但是并没有使用到，请问可以使用VIG的预训练模型吗？

**Comment by iamhankai** [comment]
创建模型后，需要自己加载权重：
https://github.com/huawei-noah/Efficient-AI-Backbones/blob/524c8d7eb610b06de179cb6235d44c99581292fe/vig_pytorch/train.py#L345

**Comment by leiRabbit1999** [comment]
十分感谢你的回复！
