### ISSUE TITLE
BN层

### ISSUE THREAD

**Issue by yebuxiu123** [huawei-noah/Efficient-AI-Backbones#231]
作者你好，我用ghostconv替换了yolov8中的普通conv层，对模型进行剪枝实验时报错AttributeError: 'GhostConv' object has no attribute 'bn'  我去看了ghostconv的代码里面也没有self.bn，请问ghostconv中是没有BN层嘛，如果没有的话是不是不能对它进行剪枝操作

**Comment by iamhankai** [comment]
你加一个BN层就行了
