### ISSUE TITLE
vig for segmentation

### ISSUE THREAD

**Issue by Yakiw** [huawei-noah/Efficient-AI-Backbones#232]
Hello, may I ask if vig can be used in semantic segmentation? If so, where should it be modified?

I tried to modify only the prediction layer, but found it difficult to restore the dimensions [1,n_filters,1,1] output before the prediction layer to the original resolution [1,classes,H,W]

**Comment by iamhankai** [comment]
使用mmsegmentation，替换里面的backbone就行了，https://github.com/open-mmlab/mmsegmentation
