### ISSUE TITLE
G-GhostNet中的Mix操作，原论文的描述和代码实现一致吗？

### ISSUE THREAD

**Issue by 12moli** [huawei-noah/Efficient-AI-Backbones#238]
作者您好，我在将G-ghostNet改进到自己的框架中时，原论文中描述的Mix操作是先进行全局平均池化后再经过一个全连接层，但是代码中是图中所示（希望我没找错）![mix操作](https://github.com/huawei-noah/Efficient-AI-Backbones/assets/102312535/8a4b27ba-d398-4cb1-a18d-5e4c8f8f15a7)，请您解释一下此处，万分感谢！

**Comment by iamhankai** [comment]
We have stated in the paper :"It may have various candidates, and here we supply a simple design"

**Comment by 12moli** [comment]
感谢您的回复！请问我可以理解成这个mix操作的可改进性很大吗？我可以尝试加入不同的模块以提升我的模型。
