### ISSUE TITLE
GhostnetV3实现插值size不匹配

### ISSUE THREAD

**Issue by weixuvg** [huawei-noah/Efficient-AI-Backbones#258]
代码第274行return out[:,:self.oup,:,:]*F.interpolate(self.gate_fn(res/self.scale),size=out.shape[-1],mode=self.inter_mode) # 'nearest'，
当out的h和w不相等时，插值会报错，是不是应该修改为
F.interpolate(self.gate_fn(res/self.scale),size=out.shape[-2],mode=self.inter_mode)

**Comment by liu-zhenhua** [comment]
是的，可以改成out.shape[-2:]
