### ISSUE TITLE
Question about the paper “ParameterNet: Parameters Are All You Need”

### ISSUE THREAD

**Issue by Polaris-F** [huawei-noah/Efficient-AI-Backbones#271]
I have been reading your recent article with great interest. However, I have a question regarding Equation 3. In the formula, the shape of 
𝑊𝑖 is described as 𝐶_out×𝐶_in×𝐻×𝑊. Could you please confirm if this is correct, or if there might be a typographical error?
![image](https://github.com/huawei-noah/Efficient-AI-Backbones/assets/49751585/2c389ab8-ea4b-485f-8436-7f13e4d64609)

**Comment by iamhankai** [comment]
I'm sorry. Its shape shoud be $`C_{out}\times C_{in}\times k\times k`$.

**Comment by Polaris-F** [comment]
Got it, Thank you~

**Comment by Polaris-F** [comment]
Got it, Thank you~
