### ISSUE TITLE
Question for parameternet!!

### ISSUE THREAD

**Issue by CC-1997** [huawei-noah/Efficient-AI-Backbones#272]
Hey, this is a nice job!!!!!! I am currently studying your paper titled "ParameterNet: Parameters Are All You Need", and I am particularly interested in the section on the complexity analysis of dynamic convolution layers. Your work provides insightful advancements in the field, and I am keen to understand the concepts presented thoroughly.

I have a question regarding the parameter count calculation for the dynamic convolution layers, specifically the term $`\(C_{\text{in}}^2\)`$ in the coefficient generation module. The paper states that the parameters required are $`\(C_{\text{in}}^2 + C_{\text{in}} \cdot M\)`$. I understand that the $`\(C_{\text{in}} \cdot M\)`$ term represents the parameters for a linear transformation from $`\(C_{\text{in}}\)`$ inputs to $`\(M\)`$ outputs (experts), but I am unsure how the $`\(C_{\text{in}}^2\)`$ term is derived, especially considering the use of adaptive average pooling which, to my understanding, should result in a parameter count of $`\(C_{\text{in}}\)`$ following the pooling operation.

Could you please clarify how the $`\(C_{\text{in}}^2\)`$ parameters are computed in this context? Any additional details on the corresponding network architecture or operations that contribute to this calculation would be greatly appreciated.

Thank you for your time and assistance. I look forward to your reply.

**Comment by iamhankai** [comment]
The coefficients is generated using a MLP with parameters of $`\(C_{\text{in}}^2 + C_{\text{in}} \cdot M\)`$. The hidden dimension of the MLP is set as $`C_{\text{in}}`$ by default.

**Comment by CC-1997** [comment]
Thanks for your answer!!!!!!

> The coefficients are generated using a MLP with parameters of \(Cin2+Cin⋅M\). The hidden dimension of the MLP is set as Cin by default.
