### ISSUE TITLE
No Pyramid ViG-B Model Weights

### ISSUE THREAD

**Issue by sunshineyang-maker** [huawei-noah/Efficient-AI-Backbones#276]
In the release pvig_b_83.66.pth.tar there is only data and data.pkl without model .pth weights. Hopefully it will be possible to release pvig_b_83.66 model weights soon.

**Comment by iamhankai** [comment]
Just renaming `.pth.tar` to `.pth` is ok

**Comment by sunshineyang-maker** [comment]
Thank you very much for your quick reply.
