### ISSUE TITLE
GhostNetV3 performance does not match paper results

### ISSUE THREAD

**Issue by Phoenix8215** [huawei-noah/Efficient-AI-Backbones#279]
@power0341 🥰Hi,

Thank you for your work on GhostNetV3. I recently trained GhostNetV3 on the Tiny-ImageNet dataset, following similar configurations to those mentioned in the paper. However, I noticed that the accuracy of GhostNetV3 is actually 2% lower than GhostNetV2, contrary to the paper’s claims of significant improvement.

I wonder if there might be any discrepancies in the settings or if some specific tricks were used in the paper that are not publicly documented. Could you provide any additional details or insights on this?

Thanks again for your contributions, and I look forward to any clarification you can provide.

**Comment by iamhankai** [comment]
Please send emails to the authors.

**Comment by Phoenix8215** [comment]
3Q for your reply ~
