### ISSUE TITLE
关于ViG验证的问题

### ISSUE THREAD

**Issue by Zsl0320** [huawei-noah/Efficient-AI-Backbones#280]
大佬，您好。目前我这里是改了一点网络去训练，但是目前遇到了问题，就是在验证预训练模型时，我使用--pretrain_path指定好路径之后，他的loss是不正常的。但是我如果--rusume这个预训练模型去评估时，他的结果就是正常的。请问这个原因是什么呢。感谢
![image](https://github.com/user-attachments/assets/3ace5609-e8c1-44d9-a643-4572b339697e)
![image](https://github.com/user-attachments/assets/1e9f1628-0a7f-42be-af4c-e582cf970202)

**Comment by Zsl0320** [comment]
我找到问题所在了，
![image](https://github.com/user-attachments/assets/c12f958e-fde2-4e86-b37d-504f3ad42e1c)
我需要额外加上state_dict = state_dict['state_dict']才可以，我没有更改train.py。为什么会这样呢

**Comment by iamhankai** [comment]
ok，那就是train.py代码写错了

**Comment by Zsl0320** [comment]
ok，感谢您的回复，谢谢
