### ISSUE TITLE
Is there a ghostnet caffe model?

### ISSUE THREAD

**Issue by Hwijune** [huawei-noah/Efficient-AI-Backbones#46]
Is there a ghostnet caffe model?

converted to darknet2caffe but not working properly in nnie 3519a,3559a.

What should I do if I want to test ghostnet or tinynet in 3519a or 3559a?

**Comment by iamhankai** [comment]
What's nnie 3519a or 3559a?

**Comment by guoqiangqi** [comment]
It maybe Hi3519A/3559A
